### ISSUE TITLE
how to use with xib?

### ISSUE THREAD

**Issue by litt1e-p** [devxoul/GenericReusable#3]
@devxoul , hi, it seems does not work with xib, can you give a hint or demo something for it? thanks.

**Comment by devxoul** [comment]
@litt1e-p, 
1. Create custom class for the prototype cells.
   
   ``` swift
   class MyCell: UITableViewCell {
     // Do nothing
   }
   ```
2. Set 'Custom Class' of the prototype cell with the custom class.
   
   <img width="269" alt="screen shot 2016-10-14 at 8 05 22 pm" src="https://cloud.githubusercontent.com/assets/931655/19385467/8dc9e414-9249-11e6-9ecf-3d25aaddefba.png">
3. Use `ReusableCell`.
   
   ``` swift
   struct Reusable {
     static let userCell = ReusableCell<MyCell>()
   }
   
   tableView.register(Reusable.myCell)
   tableView.dequeue(Reusable.myCell, for: indexPath)
   ```

**Comment by litt1e-p** [comment]
@devxoul yes, I do it as your guide, I use for collectionView, by the way, my environment: Xcode8.0, Swift3.0, iOS10. help me if you are free, thanks

**Comment by devxoul** [comment]
@litt1e-p What's the problem? Please provide me more detail.

**Comment by litt1e-p** [comment]
it cannot connect xib and collectionview. and I did not find a sample
reusable demo.

2016年10月15日星期六，Jeon Suyeol notifications@github.com 写道：

**Comment by devxoul** [comment]
@litt1e-p,

> cannot connect xib and collectionview

What does that mean?

**Comment by litt1e-p** [comment]
@devxoul, I wrote a [demo](https://github.com/litt1e-p/reusableDemo) for it, maybe it's using  `ReusableKit` something in the wrong way. please do some help for me if you are free. thanks

**Comment by devxoul** [comment]
@litt1e-p, Oh, you're not using storytboard. #4 is for you!

Could you please try with that? If that work, I'll merge and make a new release :)

**Podfile**

``` ruby
pod 'ReusableKit',
  :git => 'https://github.com/devxoul/ReusableKit',
  :branch => 'nib-support'
```

``` bash
$ pod install
```

``` diff
struct Reusable {
-   static let vcCell = ReusableCell<CollectionViewCell>()
+   static let vcCell = ReusableCell<CollectionViewCell>(nibName: "CollectionViewCell")
}
```

**Comment by litt1e-p** [comment]
@devxoul , it works now! that is great! thanks! [nib demo](https://github.com/litt1e-p/reusableDemo)

**Comment by devxoul** [comment]
@litt1e-p Thanks! [1.1.0](https://cocoapods.org/pods/ReusableKit) has released and available on CocoaPods :+1:

**Comment by litt1e-p** [comment]
@devxoul nice! thanks
